# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubContributions' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GitHubContributions
pod 'IQKeyboardManager'
pod 'DateTools'
pod 'Fabric'
pod 'Crashlytics'
pod "JazzHands"
pod 'Masonry'
pod 'Shimmer'
end

target 'TodayExtension' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TodayExtension
pod 'DateTools'
end

target 'ContributionsOnWatch Extension' do

pod 'DateTools'

end

plugin 'cocoapods-acknowledgements', :settings_bundle => true